### ISSUE TITLE
invalid desktop entry file: ' /userdata/system/.local/share/application/yuzu-config.desktop

### ISSUE THREAD

**Issue by ProPbP** [ordovice/batocera-switch#20]
Hi,
First i want to thank you for your effort and hard work you have put down to make this possible.
My friend i am on Batocera v34 and i have followed the steps, yet when i am in application and i click on the yuzu.config i get the syntax invalid desktop entry file: ' /userdata/system/.local/share/application/yuzu-config.desktop.
what am i missing here?

**Comment by ordovice** [comment]
What exactly are you trying to do?  Also, why are you not running v35?  You should be updating.  

The majority of the options for yuzu are exposed via Features

**Comment by ProPbP** [comment]
The did not start in the v35, so i downgraded to v35!

**Comment by ordovice** [comment]
Please re-upgrade to v35 and if it doesn't start, please provide the es_std logs from \system\logs

Additionally, there isn't much reason to run the yuzu-config application from the F1 menu since most of the options are already exposed in the system options for Yuzu inside EmulationStation

**Comment by ProPbP** [comment]
How do i ssh and nano the the es_std logs from \system\logs

**Comment by ProPbP** [comment]
nano the es_std logs from \system\logs es_std logs

**Comment by ordovice** [comment]
You can't use SMB?  \\<batocera ip>\share\system\logs

**Comment by ProPbP** [comment]
i have no es_std logs in that location

**Comment by ordovice** [comment]
The logs that begin with es_ (one should be err and one should be out.  Sorry, I'm not near a Batocera install right now to get the file names.

**Comment by ProPbP** [comment]
there is a log called es_launch_stderr and another called es_launch_stdout

**Comment by ProPbP** [comment]
`Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 11, in <module>
    from generators.yuzu.yuzuMainlineGenerator import YuzuMainlineGenerator
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 16, in <module>
    from utils.logger import get_logger
ImportError: cannot import name 'get_logger' from 'utils.logger' (/userdata/system/switch/configgen/utils/logger.py)`

**Comment by ProPbP** [comment]
es_launch_stdout is blank

**Comment by ordovice** [comment]
When you installed, did you upgrade over an old version?  This would happen if there was a utils folder from an old version.

**Comment by ProPbP** [comment]
i upgraded within batocerta

**Comment by ProPbP** [comment]
so from 34 to 35

**Comment by ProPbP** [comment]
really dont want to lose my game library

**Comment by ProPbP** [comment]
is there a way to overwrite the old utils folder with a new? if there is a possiblity

**Comment by ordovice** [comment]
Yeah, I'm talking about the switch add-on.  As long as you don't remove the roms\switch or the \systems\configs\yuzu folder, your library will be fine.  

I'd recommend deleting the system\switch folder entirely and re-downloading from the repo and replacing that folder to fix things properly.

**Comment by ProPbP** [comment]
should i also delete the nand/system/contents/registered?

**Comment by ordovice** [comment]
no, you shouldn't need to delete anything in the \system\configs\yuzu folder.

**Comment by ProPbP** [comment]
still cant enter the yuzu-fonfig nor enter the game in gui

**Comment by ordovice** [comment]
Upload the es_ files again after deleting the folders I've specified.  It should give a new error.

**Comment by ProPbP** [comment]
can this be a linux permission issue?

**Comment by ordovice** [comment]
No.  It is not a permission issue, but an improper upgrade completed issue.  This can happen when older versions are updated.

**Comment by ProPbP** [comment]
are we talking about the same /userdata/system/configs/yuzu?

**Comment by ProPbP** [comment]
it was hiden as you meantioned

**Comment by ProPbP** [comment]
now the es_launch_stdout log file says:
`2022-10-03 16:08:11,463 DEBUG (switchlauncher.py:115):start_rom Running system: switch
2022-10-03 16:08:11,469 DEBUG (unixSettings.py:21):__init__ Creating parser for /userdata/system/batocera.conf
2022-10-03 16:08:11,470 DEBUG (unixSettings.py:69):loadAll Looking for global.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,470 DEBUG (unixSettings.py:69):loadAll Looking for controllers.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,471 DEBUG (unixSettings.py:69):loadAll Looking for switch.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,471 DEBUG (unixSettings.py:69):loadAll Looking for switch.folder["/userdata/roms/switch"].* in /userdata/system/batocera.conf
2022-10-03 16:08:11,471 DEBUG (unixSettings.py:69):loadAll Looking for switch["Crash Team Racing Nitro-Fueled (NSP)(Base Game).nsp"].* in /userdata/system/batocera.conf
2022-10-03 16:08:11,472 DEBUG (unixSettings.py:69):loadAll Looking for display.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,472 DEBUG (Emulator.py:44):__init__ uimode: Full
2022-10-03 16:08:11,473 DEBUG (unixSettings.py:69):loadAll Looking for switch-renderer.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,473 DEBUG (unixSettings.py:69):loadAll Looking for switch["Crash Team Racing Nitro-Fueled (NSP)(Base Game).nsp"]-renderer.* in /userdata/system/batocera.conf
2022-10-03 16:08:11,474 DEBUG (switchlauncher.py:128):start_rom Settings: {'emulator': 'yuzu', 'core': 'yuzu', 'hud_support': False, 'videomode': 'max-1920x1080', 'ratio': 'full', 'video_threaded': False, 'smooth': '1', 'shaderset': 'sharp-bilinear-simple', 'rewind': False, 'bezel': 'none', 'forceNoBezel': True, 'gamemode_enable': False, 'video_frame_delay_auto': True, 'controllers.bluetooth.enabled': '1', 'controllers.ps3.enabled': '1', 'controllers.ps3.driver': 'bluez', 'controllers.xarcade.enabled': '1', 'controllers.gpio.enabled': '0', 'controllers.gpio.args': 'map=1,2', 'controllers.db9.enabled': '0', 'controllers.db9.args': 'map=1', 'controllers.gamecon.enabled': '0', 'controllers.gamecon.args': 'map=1', 'videooutput': 'HDMI-0', 'integerscale': '1', 'cpuaccuracy': '2', 'gpuaccuracy': '1', 'shaderbackend': '1', 'yuzu_backend': '1', 'language': '1', 'region': '2', 'showFPS': 'false', 'uimode': 'Full', 'emulator-forced': False, 'core-forced': False}
2022-10-03 16:08:11,474 DEBUG (switchlauncher.py:130):start_rom emulator: yuzu, core: yuzu
2022-10-03 16:08:11,525 DEBUG (switchlauncher.py:158):start_rom current video mode: 1920x1080.60.00
2022-10-03 16:08:11,525 DEBUG (switchlauncher.py:159):start_rom wanted video mode: max-1920x1080
2022-10-03 16:08:11,526 DEBUG (videoMode.py:19):changeMode setVideoMode(max-1920x1080): batocera-resolution setMode "max-1920x1080" 
2022-10-03 16:08:11,621 DEBUG (switchlauncher.py:171):start_rom resolution: 1920x1080
2022-10-03 16:08:11,622 DEBUG (Evmapy.py:42):__prepare evmapy on /userdata/system/configs/evmapy/switch.keys
2022-10-03 16:08:11,625 DEBUG (Evmapy.py:52):__prepare config file for keysfile is /var/run/evmapy/event4.json (from /userdata/system/configs/evmapy/switch.keys)
/var/run/evmapy/ready MODIFY 
2022-10-03 16:08:12,332 DEBUG (switchlauncher.py:415):runCommand command: QT_QPA_PLATFORM=xcb SDL_GAMECONTROLLERCONFIG=030000005e0400008e02000004010000,Microsoft X-Box 360 pad,platform:Linux,b:b1,a:b0,dpdown:h0.4,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,leftstick:b9,dpleft:h0.8,rightshoulder:b5,leftshoulder:b4,righttrigger:a5,rightstick:b10,dpright:h0.2,back:b6,start:b7,dpup:h0.1,y:b3,x:b2, LANGUAGE= CONSOLE=/dev/console SHLVL=1 HOME=/userdata/system OLDPWD=/ DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-x1k3irow0T,guid=431932ad6e32cb822db21370633aecbf INIT_VERSION=sysvinit- _=/usr/bin/emulationstation label=BATOCERA TERM=linux WINDOWPATH=2 BOOT_IMAGE=/boot/linux PATH=/sbin:/usr/sbin:/bin:/usr/bin RUNLEVEL=S XDG_RUNTIME_DIR=/var/run DISPLAY=:0 PREVLEVEL=N LANG=en_US.UTF-8 SHELL=/bin/sh PWD=/userdata LC_ALL=en_US.UTF-8 /userdata/system/switch/yuzu.AppImage -f -g /userdata/roms/switch/Crash Team Racing Nitro-Fueled (NSP)(Base Game).nsp
2022-10-03 16:08:12,332 DEBUG (switchlauncher.py:416):runCommand command: ['/userdata/system/switch/yuzu.AppImage', '-f', '-g', '/userdata/roms/switch/Crash Team Racing Nitro-Fueled (NSP)(Base Game).nsp']
2022-10-03 16:08:12,332 DEBUG (switchlauncher.py:417):runCommand env: {'QT_QPA_PLATFORM': 'xcb', 'SDL_GAMECONTROLLERCONFIG': '030000005e0400008e02000004010000,Microsoft X-Box 360 pad,platform:Linux,b:b1,a:b0,dpdown:h0.4,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,leftstick:b9,dpleft:h0.8,rightshoulder:b5,leftshoulder:b4,righttrigger:a5,rightstick:b10,dpright:h0.2,back:b6,start:b7,dpup:h0.1,y:b3,x:b2,', 'LANGUAGE': '', 'CONSOLE': '/dev/console', 'SHLVL': '1', 'HOME': '/userdata/system', 'OLDPWD': '/', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-x1k3irow0T,guid=431932ad6e32cb822db21370633aecbf', 'INIT_VERSION': 'sysvinit-', '_': '/usr/bin/emulationstation', 'label': 'BATOCERA', 'TERM': 'linux', 'WINDOWPATH': '2', 'BOOT_IMAGE': '/boot/linux', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin', 'RUNLEVEL': 'S', 'XDG_RUNTIME_DIR': '/var/run', 'DISPLAY': ':0', 'PREVLEVEL': 'N', 'LANG': 'en_US.UTF-8', 'SHELL': '/bin/sh', 'PWD': '/userdata', 'LC_ALL': 'en_US.UTF-8'}
2022-10-03 16:08:12,381 DEBUG (videoMode.py:19):changeMode setVideoMode(1920x1080.60.00): batocera-resolution setMode "1920x1080.60.00" 
1920x1080.60.00
2022-10-03 16:08:13,434 DEBUG (switchlauncher.py:481):<module> Exiting configgen with status -1`

**Comment by ordovice** [comment]
Re-run the updateyuzu from Ports so it redownloads the appimage :-)

**Comment by ordovice** [comment]
Did downloading yuzu again allow it to work now?

**Comment by ProPbP** [comment]
will you provide me the link to correct download link?

**Comment by ordovice** [comment]
Use the updater in Ports and it will download the correct version

**Comment by ProPbP** [comment]
i am really sorry, i understand i am really a pain for you by now!
where and how do i find this updater in ports?
is it a cmd line in terminal? a file located in a folder?

**Comment by ordovice** [comment]
Did you install ALL the files from this github when upgrading your old install?  If you had, there are scripts that drop in the roms/ports folder that include updaters for yuzu, yuzuea, ryujinx, and ryujinx-avalonia ..

**Comment by ProPbP** [comment]
yes i did delete the old folders like you told me to, and retransfered the build to \\BATOCERA\share

**Comment by ordovice** [comment]
So browse to ports in Emulationstation and you should see the updaters ..

**Comment by ProPbP** [comment]
Its getting scary, i don't see anything called update or updater?

**Comment by ordovice** [comment]
It's called updateyuzu ..

**Comment by ProPbP** [comment]
there is no such file called updateyuzu in \\BATOCERA\share\system\configs\emulationstation

**Comment by ordovice** [comment]
Literally, using your controller and the gui.  This is not something that needs to be done via Terminal, SMB, etc.

**Comment by ProPbP** [comment]
I have some new!
idiot like me as tiered as i am after nights of staying up to find the issue with no luck, after all the steps you showed me. i never restarted the system.
after restarting the batocera everything works like a charm!

**Comment by ProPbP** [comment]
I am really grateful to you, we need more people like you out there!
I thank you my friend, and i wish you good luck and success!

**Comment by brunnels** [comment]
@ordovice I had this same issue.  Fresh batocera v35.  Ran the update script and it installed the flatpacks.  Rebooted.  Same error message.

What I found to be the problem is the 4 executables in `/userdata/system/switch/extra/` where not set as executable.  chmod +x on the 4 fixed the problem.
