### ISSUE TITLE
Games not starting anymore via Batocera/Emulationstation since 1 day

### ISSUE THREAD

**Issue by wenzel-k** [ordovice/batocera-switch#243]
I am using the beta version of batocera and everything was working fine 2 days ago.
But i guess since the latest beta update i did yesterday (x86_64 - 39-dev-8242b59374 2023/11/12 00:55), i can not start the games from the main menu anymore. It still works via file manager -> Applications -> yuzu config.

The es_launch_stderr.log shows the following error:
```
2023-11-12 19:32:57,539 ERROR (switchlauncher.py:599):<module> configgen exception:
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 597, in <module>
    exitcode = main(args, maxnbplayers)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/userdata/system/switch/configgen/switchlauncher.py", line 109, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/userdata/system/switch/configgen/switchlauncher.py", line 232, in start_rom
    if generator.getMouseMode(system.config):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Generator.getMouseMode() missing 1 required positional argument: 'rom'

```

Could this be related to any recent changes on batocera-switch?

Thanks for looking into this and best regards
Wenzel

**Comment by uureel** [comment]
fix merged, run the updater
