### ISSUE TITLE
Batocera 39/40 wont launch game through Batocera, but will going directly to the App.

### ISSUE THREAD

**Issue by natemac** [ordovice/batocera-switch#283]
I've tried this on Stable 39 and Beta 40. my games show up in the batocera menu but when I launch them it just kicks me back to the menu. If I go into the F1 menu and launch Ryujix and the game, the game will launch.

I've updated and downgraded Batocera, I've deleted the System/Switch folder. and re-ran the command, none of this troubleshooting has fixed the issue.

I'm on a SteamDeck, this has worked in the past I just recently loaded Batocera up to find this issue.

es_launch_stderr.log
`evmapy: no process found
2024-06-30 08:27:22,973 ERROR (switchlauncher.py:617):<module> configgen exception: 
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 615, in <module>
    exitcode = main(args, maxnbplayers)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/userdata/system/switch/configgen/switchlauncher.py", line 122, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/userdata/system/switch/configgen/switchlauncher.py", line 290, in start_rom
    cmd = generator.generate(system, rom, playersControllers, gameResolution)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/userdata/system/switch/configgen/generators/ryujinx/ryujinxMainlineGenerator.py", line 49, in generate
    RyujinxMainlineGenerator.writeRyujinxConfig(RyujinxConfig, system, playersControllers)
  File "/userdata/system/switch/configgen/generators/ryujinx/ryujinxMainlineGenerator.py", line 402, in writeRyujinxConfig
    myid = uuid.UUID(sdl_mapping['guid'])
                     ~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
`

**Comment by natemac** [comment]
Turning off Auto Controller Config, let me launch from Batocera and manually setting the controller input seems to fixed the issue, but everything seems to have almost a 1 second delay.

**Comment by natemac** [comment]
I did a fresh install of Batocera 39 and still have the same issue.

**Comment by kryptk2010** [comment]
Only have this issue on V41, V40 works fine without issues but from that last beta they uploaded it killed switch from the menu but works with f1 > applications.

**Comment by AshenFFXI** [comment]
Can confirm kryptic2010's issue. v39, v40 and All 41 butterfly releases were fine up until yesterday and now from ES you get immediately booted to the menu when trying to launch a game. Everything seems to be working via F1 -> applications.

**Comment by kryptk2010** [comment]
Wonder if it is linked to the hotkey changes and the hotkeygen introduction.
source "$BR2_EXTERNAL_BATOCERA_PATH/package/batocera/utils/hotkeygen/Config.in"
