### ISSUE TITLE
Discord Integration=AUTO is broken

### ISSUE THREAD

**Issue by uureel** [ordovice/batocera-switch#34]
while both OFF and ON work

[root@BATOCERA /userdata/system]# stderr
killall: evmapy: no process killed
2022-11-15 17:51:08,433 ERROR (switchlauncher.py:479):<module> configgen exception:
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 477, in <module>
    exitcode = main(args, maxnbplayers)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 94, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 200, in start_rom
    cmd = generators[system.config['emulator']].generate(system, rom, playersControllers, gameResolution)
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 96, in generate
    YuzuMainlineGenerator.writeYuzuConfig(yuzuConfig,beforeyuzuConfig, system, playersControllers)
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 215, in writeYuzuConfig
    yuzuConfig.set("Core", "enable_discord_presence", system.config["yuzu_enable_discord_presence"])
KeyError: 'yuzu_enable_discord_presence'

**Comment by ordovice** [comment]
Fix pushed.  Missed a variable set before.

**Comment by uureel** [comment]
confirmed working, thx
