### ISSUE TITLE
ImportError for switchlauncher.py

### ISSUE THREAD

**Issue by n-sudo** [ordovice/batocera-switch#6]
Description: 
After attempting to launch a game, I am immediately returned to emulationstation. Running switchlauncher.py from the command line results in the following error: 

```
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 8, in <module>
    from Evmapy import Evmapy
  File "/userdata/system/switch/configgen/Evmapy.py", line 8, in <module>
    import evdev
  File "/userdata/system/switch/configgen/evdev/__init__.py", line 7, in <module>
    from evdev.device import DeviceInfo, InputDevice, AbsInfo
  File "/userdata/system/switch/configgen/evdev/device.py", line 6, in <module>
    from evdev import _input, ecodes, util
  File "/userdata/system/switch/configgen/evdev/ecodes.py", line 44, in <module>
    from evdev import _ecodes
ImportError: cannot import name '_ecodes' from partially initialized module 'evdev' (most likely due to a circular import) (/userdata/system/switch/configgen/evdev/__init__.py)
```

**Comment by foclabroc** [comment]
delete EVDEV folder in /system/switch/configgen/

**Comment by ordovice** [comment]
This is a known issue. I am working on an updated version for v34. I'll close this once I have a working version.

**Comment by ordovice** [comment]
Can you please download the v34 version as it revamps what it's calling from the OS and what is standalone now

**Comment by ordovice** [comment]
Resolved in v34 version
