### ISSUE TITLE
Batocera v35 OSError: [Errno 95] (SMB Wont work as it should) please close it its a batocera problem

### ISSUE THREAD

**Issue by RiDDiX** [ordovice/batocera-switch#92]
killall: evmapy: no process killed
2023-02-08 18:49:10,528 ERROR (switchlauncher.py:589):<module> configgen exception: 
Traceback (most recent call last):
  File "/userdata/system/switch/configgen/switchlauncher.py", line 587, in <module>
    exitcode = main(args, maxnbplayers)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 102, in main
    return start_rom(args, maxnbplayers, args.rom, args.rom)
  File "/userdata/system/switch/configgen/switchlauncher.py", line 262, in start_rom
    cmd = generator.generate(system, rom, playersControllers, gameResolution)
  File "/userdata/system/switch/configgen/generators/yuzu/yuzuMainlineGenerator.py", line 61, in generate
    st = os.symlink("/userdata/system/configs/yuzu","/userdata/system/.local/share/yuzu")
OSError: [Errno 95] Operation not supported: '/userdata/system/configs/yuzu' -> '/userdata/system/.local/share/yuzu'

**Comment by RiDDiX** [comment]
Sorry fixed it myself. Same problem with Kodi network shares dont work as espected....

**Comment by uureel** [comment]
batocera doesn't support symlinks on netshares
